# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(638, 732)
        MainWindow.setStyleSheet("/* Main Window */\n"
"QMainWindow {\n"
"    background-color: rgb(70, 19, 85);\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"}\n"
"\n"
"/* Buttons */\n"
"QPushButton {\n"
"    background-color: #6c5ce7;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 10px 20px;\n"
"    font-weight: bold;\n"
"    font-size: 19px;\n"
"    min-width: 100px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5649c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3d36a0;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #2d2d4d;\n"
"    color: #7a7a8c;\n"
"}\n"
"\n"
"/* Line Edits */\n"
"QLineEdit {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: white;\n"
"    border: 2px solid #3d3d5a;\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;\n"
"    selection-background-color: #6c5ce7;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: gray;\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    font-size: 19px;\n"
"}\n"
"\n"
"QLabel#headerLabel {\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Combo Boxes */\n"
"QComboBox {\n"
"    background-color: #1a1a2e;\n"
"    border: 2px solid #3d3d5a;\n"
"    border-radius: 6px;\n"
"    padding: 8px;\n"
"    color: white;\n"
"    min-width: 120px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border-color: #6c5ce7;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left: 1px solid #3d3d5a;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #1a1a2e;\n"
"    color: white;\n"
"    selection-background-color: #6c5ce7;\n"
"    outline: none;\n"
"}\n"
"\n"
"/* Scroll Bars */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #1a1a2e;\n"
"    width: 10px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #6c5ce7;\n"
"    min-height: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    height: 0;\n"
"}\n"
"\n"
"/* Progress Bar */\n"
"QProgressBar {\n"
"    border: 1px solid #3d3d5a;\n"
"    border-radius: 4px;\n"
"    text-align: center;\n"
"    color: white;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #6c5ce7;\n"
"    width: 10px;\n"
"}\n"
"\n"
"/* Tab Widget */\n"
"QTabWidget::pane {\n"
"    border: none;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: #1a1a2e;\n"
"    color: #a29bfe;\n"
"    padding: 15px 60px;\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    border: 1px solid #3d3d5a;\n"
"    border-bottom: none;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #6c5ce7;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Table View */\n"
"QTableView {\n"
"    background-color: #1a1a2e;\n"
"    border: 1px solid #3d3d5a;\n"
"    gridline-color: #3d3d5a;\n"
"    alternate-background-color: #252541;\n"
"    selection-background-color: #6c5ce7;\n"
"    color: white;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #252541;\n"
"    color: #a29bfe;\n"
"    padding: 8px;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Menu Bar */\n"
"QMenuBar {\n"
"    background-color: #0a0a1a;\n"
"    color: white;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #6c5ce7;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #1a1a2e;\n"
"    border: 1px solid #3d3d5a;\n"
"    color: white;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #6c5ce7;\n"
"}\n"
"\n"
"/* Status Bar */\n"
"QStatusBar {\n"
"    background-color: #1a1a2e;\n"
"    color: #a29bfe;\n"
"    border-top: 1px solid #3d3d5a;\n"
"}\n"
"\n"
"/* Tool Tips */\n"
"QToolTip {\n"
"    background-color: #6c5ce7;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 5px;\n"
"    opacity: 230;\n"
"}\n"
"QStackedWidget{\n"
"    color: white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 631, 731))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("color: rgb(244, 244, 244);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(40, 30, 561, 311))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-radius: 10px;\n"
"\n"
"text-align: center;")
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setPlainText("")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(40, 390, 421, 41))
        self.lineEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(80, 360, 501, 21))
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 390, 140, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 530, 291, 81))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(250, 440, 140, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 30, 561, 331))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-radius: 10px;\n"
"\n"
"text-align: center;")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(170, 530, 301, 81))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(0, 400, 631, 41))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AVIATO: ZENPAY"))
        self.label_2.setText(_translate("MainWindow", "Вводите сюда секретные слова   "))
        self.pushButton_2.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_3.setText(_translate("MainWindow", "ВОЙТИ В КОШЕЛЕК"))
        self.pushButton_4.setText(_translate("MainWindow", "Убрать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Вход"))
        self.pushButton.setText(_translate("MainWindow", "СОЗДАТЬ КОШЕЛЕК"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Перепишите куда-то эти слова, они вам пригодятся для входа </p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Регистрация"))
