# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'post_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class PostMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(593, 545)
        MainWindow.setStyleSheet("/* Main Window */\n"
"QMainWindow {\n"
"    background-color: rgb(70, 19, 85);\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"}\n"
"\n"
"/* Buttons */\n"
"QPushButton {\n"
"    background-color: #6c5ce7;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 10px 20px;\n"
"    font-weight: bold;\n"
"    font-size: 19px;\n"
"    min-width: 100px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5649c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3d36a0;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #2d2d4d;\n"
"    color: #7a7a8c;\n"
"}\n"
"\n"
"/* Line Edits */\n"
"QLineEdit {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: white;\n"
"    border: 2px solid #3d3d5a;\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;\n"
"    selection-background-color: #6c5ce7;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: gray;\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    font-size: 19px;\n"
"}\n"
"\n"
"QLabel#headerLabel {\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Combo Boxes */\n"
"QComboBox {\n"
"    background-color: #1a1a2e;\n"
"    border: 2px solid #3d3d5a;\n"
"    border-radius: 6px;\n"
"    padding: 8px;\n"
"    color: white;\n"
"    min-width: 120px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border-color: #6c5ce7;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left: 1px solid #3d3d5a;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #1a1a2e;\n"
"    color: white;\n"
"    selection-background-color: #6c5ce7;\n"
"    outline: none;\n"
"}\n"
"\n"
"/* Scroll Bars */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #1a1a2e;\n"
"    width: 10px;\n"
"    margin: 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #6c5ce7;\n"
"    min-height: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    height: 0;\n"
"}\n"
"\n"
"/* Progress Bar */\n"
"QProgressBar {\n"
"    border: 1px solid #3d3d5a;\n"
"    border-radius: 4px;\n"
"    text-align: center;\n"
"    color: white;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #6c5ce7;\n"
"    width: 10px;\n"
"}\n"
"\n"
"/* Tab Widget */\n"
"QTabWidget::pane {\n"
"    border: none;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: #1a1a2e;\n"
"    color: #a29bfe;\n"
"    padding: 15px 60px;\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    border: 1px solid #3d3d5a;\n"
"    border-bottom: none;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #6c5ce7;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Table View */\n"
"QTableView {\n"
"    background-color: #1a1a2e;\n"
"    border: 1px solid #3d3d5a;\n"
"    gridline-color: #3d3d5a;\n"
"    alternate-background-color: #252541;\n"
"    selection-background-color: #6c5ce7;\n"
"    color: white;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #252541;\n"
"    color: #a29bfe;\n"
"    padding: 8px;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Menu Bar */\n"
"QMenuBar {\n"
"    background-color: #0a0a1a;\n"
"    color: white;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #6c5ce7;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #1a1a2e;\n"
"    border: 1px solid #3d3d5a;\n"
"    color: white;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #6c5ce7;\n"
"}\n"
"\n"
"/* Status Bar */\n"
"QStatusBar {\n"
"    background-color: #1a1a2e;\n"
"    color: #a29bfe;\n"
"    border-top: 1px solid #3d3d5a;\n"
"}\n"
"\n"
"/* Tool Tips */\n"
"QToolTip {\n"
"    background-color: #6c5ce7;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 5px;\n"
"    opacity: 230;\n"
"}\n"
"QStackedWidget{\n"
"    color: white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-10, 70, 601, 41))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 20, 311, 21))
        self.label.setStyleSheet("color: rgb(255, 245, 240);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 30, 141, 31))
        self.label_2.setStyleSheet("color: rgb(255, 245, 240);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 50, 261, 21))
        self.label_3.setStyleSheet("color: rgb(255, 245, 240);")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 190, 221, 51))
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(140, 140, 421, 16))
        self.label_4.setStyleSheet("color: rgb(255, 245, 240);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 110, 431, 16))
        self.label_5.setStyleSheet("color: rgb(255, 245, 240);")
        self.label_5.setObjectName("label_5")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 260, 591, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(200, 360, 371, 41))
        self.lineEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(280, 320, 271, 31))
        self.label_7.setStyleSheet("color: rgb(255, 245, 240);")
        self.label_7.setObjectName("label_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 360, 131, 41))
        self.lineEdit_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 320, 71, 31))
        self.label_8.setStyleSheet("color: rgb(255, 245, 240);")
        self.label_8.setObjectName("label_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 460, 221, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Ваш кошелек: "))
        self.label_2.setText(_translate("MainWindow", "AVIATO ZENPAY"))
        self.label_3.setText(_translate("MainWindow", "Баланс:"))
        self.pushButton.setText(_translate("MainWindow", "Майнить блок"))
        self.label_4.setText(_translate("MainWindow", "Хэш сложность:"))
        self.label_5.setText(_translate("MainWindow", "Намайнено блоков:"))
        self.label_7.setText(_translate("MainWindow", "Кошелек получателя:"))
        self.label_8.setText(_translate("MainWindow", "Кол-во:"))
        self.pushButton_2.setText(_translate("MainWindow", "Перевести "))
