# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1202, 671)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/future/Pictures/aerostat_vozdushnyj_shar_nebo_86980_1920x1080.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("\n"
"/* Кнопки */\n"
"QPushButton {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #d3d3d3;\n"
"    border-radius: 4px;\n"
"    padding: 5px 12px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e9e9e9;\n"
"    border-color: #b5b5b5;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 1px solid #1e90ff;\n"
"    outline: none;\n"
"}\n"
"\n"
"/* Акцентные кнопки */\n"
"QPushButton[accent=\"true\"] {\n"
"    background-color: #1e90ff;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton[accent=\"true\"]:hover {\n"
"    background-color: #1c7fe6;\n"
"}\n"
"\n"
"QPushButton[accent=\"true\"]:pressed {\n"
"    background-color: #1a6fcc;\n"
"}\n"
"\n"
"/* Поля ввода */\n"
"QLineEdit, QTextEdit, QPlainTextEdit, QComboBox {\n"
"    border: 1px solid #d3d3d3;\n"
"    border-radius: 4px;\n"
"    padding: 5px 8px;\n"
"    background-color: white;\n"
"    selection-background-color: #1e90ff;\n"
"    selection-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus, QTextEdit:focus, QPlainTextEdit:focus, QComboBox:focus {\n"
"    border: 1px solid #1e90ff;\n"
"    outline: none;\n"
"}\n"
"\n"
"/* Чекбоксы и радиокнопки */\n"
"QCheckBox::indicator, QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked, QRadioButton::indicator:checked {\n"
"    background-color: #1e90ff;\n"
"    border: 1px solid #1c7fe6;\n"
"}\n"
"\n"
"/* Полосы прокрутки */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #f5f5f5;\n"
"    width: 10px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #d3d3d3;\n"
"    min-height: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #b5b5b5;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* Вкладки */\n"
"QTabWidget::pane {\n"
"    border: 1px solid #d3d3d3;\n"
"    top: -1px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: #f5f5f5;\n"
"    border: 1px solid #d3d3d3;\n"
"    padding: 5px 12px;\n"
"    margin-right: 2px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: white;\n"
"    border-bottom-color: white;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: #e9e9e9;\n"
"}\n"
"\n"
"/* Меню */\n"
"QMenuBar {\n"
"    background-color: #ffffff;\n"
"    border-bottom: 1px solid #d3d3d3;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #e9e9e9;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: white;\n"
"    border: 1px solid #d3d3d3;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #1e90ff;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Прогресс-бар */\n"
"QProgressBar {\n"
"    border: 1px solid #d3d3d3;\n"
"    border-radius: 4px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #1e90ff;\n"
"    width: 10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(350, 150, 441, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("border-radius: 10px;\n"
"background-color: rgba(255, 255, 255, 0.95);")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 70, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Arial,sans-serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(30, 190, 401, 31))
        self.lineEdit.setInputMask("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 280, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Arial,sans-serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(50, 30, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Arial,sans-serif")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 150, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(410, 560, 301, 28))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AVIATO:ENTER"))
        self.label.setText(_translate("MainWindow", "Создать учетную запись"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "test@gmail.com"))
        self.pushButton_2.setText(_translate("MainWindow", "Далее"))
        self.label_2.setText(_translate("MainWindow", "/// AVIATO GROUP"))
        self.label_3.setText(_translate("MainWindow", "Введите почту:"))
        self.pushButton.setText(_translate("MainWindow", "У меня уже есть аккаунт"))
