# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buy.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1217, 754)
        MainWindow.setStyleSheet("QSpinBox { text-align: center; }\n"
"\n"
"/* Кнопки */\n"
"QPushButton {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #d3d3d3;\n"
"    border-radius: 4px;\n"
"    padding: 5px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e9e9e9;\n"
"    border-color: #b5b5b5;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9d9d9;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    border: 1px solid #1e90ff;\n"
"    outline: none;\n"
"}\n"
"\n"
"/* Акцентные кнопки */\n"
"QPushButton[accent=\"true\"] {\n"
"    background-color: #1e90ff;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton[accent=\"true\"]:hover {\n"
"    background-color: #1c7fe6;\n"
"}\n"
"\n"
"QPushButton[accent=\"true\"]:pressed {\n"
"    background-color: #1a6fcc;\n"
"}\n"
"\n"
"/* Поля ввода */\n"
"QLineEdit, QTextEdit, QPlainTextEdit, QComboBox {\n"
"    border: 1px solid #d3d3d3;\n"
"    border-radius: 4px;\n"
"    padding: 5px 8px;\n"
"    background-color: white;\n"
"    selection-background-color: #1e90ff;\n"
"    selection-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus, QTextEdit:focus, QPlainTextEdit:focus, QComboBox:focus {\n"
"    border: 1px solid #1e90ff;\n"
"    outline: none;\n"
"}\n"
"\n"
"/* Чекбоксы и радиокнопки */\n"
"QCheckBox::indicator, QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked, QRadioButton::indicator:checked {\n"
"    background-color: #1e90ff;\n"
"    border: 1px solid #1c7fe6;\n"
"}\n"
"\n"
"/* Полосы прокрутки */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #f5f5f5;\n"
"    width: 10px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #d3d3d3;\n"
"    min-height: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #b5b5b5;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* Вкладки */\n"
"QTabWidget::pane {\n"
"    border: 1px solid #d3d3d3;\n"
"    top: -1px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: #f5f5f5;\n"
"    border: 1px solid #d3d3d3;\n"
"    padding: 5px 12px;\n"
"    margin-right: 2px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: white;\n"
"    border-bottom-color: white;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: #e9e9e9;\n"
"}\n"
"\n"
"/* Меню */\n"
"QMenuBar {\n"
"    background-color: #ffffff;\n"
"    border-bottom: 1px solid #d3d3d3;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #e9e9e9;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: white;\n"
"    border: 1px solid #d3d3d3;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #1e90ff;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Прогресс-бар */\n"
"QProgressBar {\n"
"    border: 1px solid #d3d3d3;\n"
"    border-radius: 4px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #1e90ff;\n"
"    width: 10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 20, 411, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 110, 1121, 621))
        self.frame.setStyleSheet("border-radius: 10px;\n"
"background-color: rgba(255, 255, 255, 0.95);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.line_5 = QtWidgets.QFrame(self.frame)
        self.line_5.setGeometry(QtCore.QRect(30, 120, 401, 371))
        self.line_5.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(50, 150, 321, 321))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.line_6 = QtWidgets.QFrame(self.frame)
        self.line_6.setGeometry(QtCore.QRect(30, 60, 401, 51))
        self.line_6.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(140, 20, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(40, 70, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(320, 70, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(30, 520, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(30, 110, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.line_8 = QtWidgets.QFrame(self.frame)
        self.line_8.setGeometry(QtCore.QRect(190, 500, 241, 101))
        self.line_8.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(370, 500, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(200, 510, 161, 81))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setGeometry(QtCore.QRect(460, 90, 611, 511))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(50, 50, 531, 71))
        self.line.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(200, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(70, 70, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.tab)
        self.dateTimeEdit.setGeometry(QtCore.QRect(360, 70, 171, 31))
        self.dateTimeEdit.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.dateTimeEdit.setDate(QtCore.QDate(2025, 1, 1))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(50, 150, 531, 101))
        self.line_2.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(170, 160, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(70, 200, 121, 31))
        self.comboBox.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(200, 200, 161, 31))
        self.comboBox_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab)
        self.comboBox_3.setGeometry(QtCore.QRect(370, 200, 201, 31))
        self.comboBox_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(50, 280, 531, 51))
        self.line_3.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(60, 290, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.spinBox = QtWidgets.QSpinBox(self.tab)
        self.spinBox.setGeometry(QtCore.QRect(350, 290, 221, 31))
        self.spinBox.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"text-align:center;")
        self.spinBox.setMinimum(1)
        self.spinBox.setObjectName("spinBox")
        self.line_7 = QtWidgets.QFrame(self.tab)
        self.line_7.setGeometry(QtCore.QRect(50, 360, 531, 51))
        self.line_7.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(70, 370, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.comboBox_7 = QtWidgets.QComboBox(self.tab)
        self.comboBox_7.setGeometry(QtCore.QRect(300, 370, 271, 31))
        self.comboBox_7.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.line_4 = QtWidgets.QFrame(self.tab_2)
        self.line_4.setGeometry(QtCore.QRect(40, 90, 541, 111))
        self.line_4.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(210, 20, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(190, 100, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_4.setGeometry(QtCore.QRect(60, 150, 101, 31))
        self.comboBox_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_5.setGeometry(QtCore.QRect(180, 150, 171, 31))
        self.comboBox_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_6.setGeometry(QtCore.QRect(360, 150, 211, 31))
        self.comboBox_6.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(670, 20, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 230, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(380, 330, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AVIATO:MAIN"))
        self.label.setText(_translate("MainWindow", "ЗАКАЗ БИЛЕТА"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p>Данные полета:</p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "Время полета:"))
        self.label_12.setText(_translate("MainWindow", "00:00:00"))
        self.pushButton.setText(_translate("MainWindow", "Оформить"))
        self.label_9.setText(_translate("MainWindow", "Карта:"))
        self.label_14.setText(_translate("MainWindow", "Цена:"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>Параметры вылета:</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Время вылета:"))
        self.label_4.setText(_translate("MainWindow", "Место вылета:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Страна"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Город"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Название аэропорта"))
        self.label_5.setText(_translate("MainWindow", "Кол-во пассажиров:"))
        self.label_13.setText(_translate("MainWindow", "Доп. параметры:"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "Выбор параметра"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "Гравитационный двигатель"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Параметры вылета"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p>Параметры прилета:</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Место прилета:"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Страна"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Город"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Название аэропорта"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Параметры прилета"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p>Параметры полета:</p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "➕\n"
"🔍"))
        self.pushButton_3.setText(_translate("MainWindow", "🔍\n"
"➖"))
